development:
  adapter: mysql
  database: tessaanntaylor_development
  host: localhost
  username: root
  password: 
  timeout: 5000

test:
  adapter: mysql
  database: tessaanntaylor_test
  host: localhost
  username: root
  password: 
  timeout: 5000

production:
  adapter: postgresql
  database: tessaanntaylor_production
  host: localhost
  username: root
  password: 
  timeout: 5000
