# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tessa
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: tessaanntaylor_development

test:
  <<: *default
  database: tessaanntaylor_test
  
production:
  <<: *default
  database: tessaanntaylor_production